public with sharing class FilterConstant {
    public static final String USER_STORY='User_Story__c';
    public static final String FIELDTYPE_BOOLEAN = 'BOOLEAN';
    public static final String FIELDTYPE_DOUBLE = 'DOUBLE';
    public static final String FIELDTYPE_PICKLIST = 'PICKLIST';
    public static final String OPERATOR_LIKE = 'Like';
    public static final String OPERATOR_NOT_LIKE = '!Like';
    public static final String OPERATOR_STARTS_WITH = 'StartsWith';
    public static final String OWNER_STRING = 'My User Stories';
    public static final String INVALID_STRING = '-1000';
}